### ISSUE TITLE
英字略称への読み追加

### ISSUE THREAD

**Issue by eggplants** [nandenjin/itfdic#2]
biol~cccは英単語と言う訳ではないので、英語としての読みと併存して一般のカタカナ読みを追加しても良いと思いました
ref: https://twitter.com/egpl0/status/1289457056672440320

**Comment by nandenjin** [comment]
実際に会話で使われる読みを登録するのが良いというのは全くその通りなので方向性に異論はないのですが、他の辞書で略語などについてどのような読みの登録がされているのかをよく知らないため少し気になります。

手が空いた時に探してみたいと思いますが、もし実例をご存知でしたらどなたでもご報告いただけると嬉しいです！

**Comment by nandenjin** [comment]
[mecab-ipadic-NEologd](https://github.com/neologd/mecab-ipadic-neologd)で英字の略語にかな読みをつけている（[例](https://github.com/neologd/mecab-ipadic-neologd/blob/master/seed/mecab-user-dict-seed.20200709.csv.xz)）のを確認したので、itfdicでもこの方針で良いかと思われます:+1:

**Comment by nandenjin** [comment]
de667c362096b60df5d9761136b1a24323f61b68 / [`r200804_1744`](https://github.com/nandenjin/itfdic/releases/tag/r200804_1744) で修正しました 🎉 🙇  問題があればReopen願います〜
